version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6378:6379'
  db:
    image: postgres:latest
    container_name: db
    environment:
      - PD_DATA=/var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    tty: true
    command: >
      sh -c "sleep 3 &&  python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
      build: .
      container_name: celery
      tty: true
      env_file:
        - .env
      command: sh -c "sleep 5 && celery -A config worker -l INFO"
      depends_on:
          - redis
          - app

  celery_beat:
    build: .
    container_name: celery_beat
    tty: true
    env_file:
      - .env
    command: sh -c "sleep 10 && celery -A config beat -l info -S django"
    depends_on:
      - celery
      - redis
      - app
volumes:
  pg_data:
